### ISSUE TITLE
Add dCKB support on Testnet and Mainnet

### ISSUE THREAD

**Issue by Kuzirashi** [nervosnetwork/light-godwoken#122]
One of the apps - https://app.hadouken.finance/ - deployed on Godwoken Mainnet v0 is using dCKB. It would be great if Godwoken Bridge also supported dCKB (both on Testnet and Mainnet).

dCKB erc20 address on testnet v1.1: 0x7e54f7324902B72334827F40f613116F06a88845 (https://nervos.gitbook.io/layer-2-evm/ecosystem/tokens)

**Comment by zhangyouxin** [comment]
> dCKB erc20 address on testnet v1.1: 0x7e54f7324902B72334827F40f613116F06a88845 (https://nervos.gitbook.io/layer-2-evm/ecosystem/tokens)

Is there any info about this token on CKB layer 1 testnet? I could use the SUDT args of this SUDT also

**Comment by Kuzirashi** [comment]
> > dCKB erc20 address on testnet v1.1: 0x7e54f7324902B72334827F40f613116F06a88845 (https://nervos.gitbook.io/layer-2-evm/ecosystem/tokens)
> 
> Is there any info about this token on CKB layer 1 testnet? I could use the SUDT args of this SUDT also

dCKB SUDT args on Layer 1 testnet: 0xc43009f083e70ae3fee342d59b8df9eec24d669c1c3a3151706d305f5362c37e

cc @zhangyouxin

**Comment by zhangyouxin** [comment]
This PR https://github.com/zhangyouxin/light-godwoken/pull/130 has added dCKB to testnet, sicne I don't have this test token, could you help test it here: https://light-godwoken-git-dckb-cryptape.vercel.app/

cc @Kuzirashi

**Comment by Kuzirashi** [comment]
I left comments in #130. 

Can you please also add dCKB on mainnet v0?

https://gwscan.com/token/249

Mainnet info:
dCKB ERC20 contract address: [0x53a1964a163f64da59efe6a802e35b5529d078e2](https://gwscan.com/account/0x53a1964a163f64da59efe6a802e35b5529d078e2)
SUDT Type args (Issuer lock hash): 0xe5451c05231e1df43e4b199b5d12dbed820dfbea2769943bb593f874526eeb55 (example transaction with dCKB on mainnet: https://explorer.nervos.org/transaction/0x123b14b590041743075ed2ef2be927a7adf311fd9b40efbdbf7e16ddf5f59e24#1)

cc @zhangyouxin

**Comment by Kuzirashi** [comment]
On Mainnet dCKB transfers work great!
