### ISSUE TITLE
mainnet: godwoken v0  cant't withdrawal  sudt  and show max: 0

### ISSUE THREAD

**Issue by tianlitao** [nervosnetwork/light-godwoken#156]
![image](https://user-images.githubusercontent.com/7892962/176854505-68131047-e89a-4a3e-9302-4005de197150.png)
![image](https://user-images.githubusercontent.com/7892962/176854598-7c0abf64-ae4f-4598-8afc-4ca46fc463f8.png)

**Comment by zhangyouxin** [comment]
@tianlitao Hello, thanks for reporting this bug, could you please retry it on preview here:

https://light-godwoken-mainnet-git-fork-zhangyouxin-fix-f40357-cryptape.vercel.app/#/v0

After some confirmation the preview deploy will be promoted to production.

**Comment by tianlitao** [comment]
> @tianlitao Hello, thanks for reporting this bug, could you please retry it on preview here:
> 
> https://light-godwoken-mainnet-git-fork-zhangyouxin-fix-f40357-cryptape.vercel.app/#/v0
> 
> After some confirmation the preview deploy will be promoted to production.

I used this link to operate successfully

**Comment by zhangyouxin** [comment]
Closed by https://github.com/nervosnetwork/light-godwoken/pull/157
