### ISSUE TITLE
A `0.1 COOP` deposit was not listed in Completed list

### ISSUE THREAD

**Issue by Flouse** [nervosnetwork/light-godwoken#183]
![image](https://user-images.githubusercontent.com/1297478/186355251-c62b4703-c35f-453f-af04-86dd43a496af.png)

deposit 0.1 COOP transaction：https://explorer.nervos.org/transaction/0xb4f18343befbf7e90aac35d0f8993bf7599f5fa2d59658bd915a405e3cac8ba1
deposit 1 COOP transaction：https://explorer.nervos.org/transaction/0x68adff5ea5c8d34d6deaa9c066548badd5148d2137d9d4f7c58f2ae6e1e501c7

**Comment by ShookLyngs** [comment]
Shoulb be fixed in:
- https://github.com/nervosnetwork/light-godwoken/pull/185
