### ISSUE TITLE
Testnet_v0 is officially deprecated

### ISSUE THREAD

**Issue by ShookLyngs** [nervosnetwork/light-godwoken#184]
## [Deprecating old Godwoken v0 testnet](https://talk.nervos.org/t/deprecating-old-godwoken-v0-testnet/6718)
The `testnet_v0` of Godwoken is officially [deprecated](https://github.com/nervosnetwork/godwoken-info/).

We should keep up with:
- Remove v0 testcases from light-godwoken or any replacement? @homura @Flouse 
- Disable actions on testnet_v0 pages

**Comment by Flouse** [comment]
> * Remove v0 testcases from light-godwoken or any replacement? @homura @Flouse
> * Disable actions on testnet_v0 pages

yes.
But I think we need a new test case which cover the workflow of fast withdrawal from mainnet_v0 to mainnet_v1, especially when we are refactoring light-godwoken.

**Comment by ShookLyngs** [comment]
Testcases will be hidden in:
- https://github.com/nervosnetwork/light-godwoken/pull/185
